[versions]
kotlin = "2.2.21"
spring-boot = "4.0.0"
restassured = "5.5.6"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
restAssured-core = { module = "io.rest-assured:rest-assured", version.ref = "restassured" }
restAssured-kotlin = { module = "io.rest-assured:kotlin-extensions", version.ref = "restassured" }
passay = { module = "org.passay:passay", version.require = "1.6.6" }
springdoc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.require = "3.0.0" }

[plugins]
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.require = "1.1.7" }
